/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author USER
 */
public class matchesFrm extends javax.swing.JFrame {

    /**
     * Creates new form matchesFrm
     */
    public matchesFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarEstudiantes3 = new presentacion.botonCircular();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnInicio3 = new presentacion.botonCircular();
        btnMatches3 = new presentacion.botonCircular();
        btnMensajes3 = new presentacion.botonCircular();
        btnPerfil3 = new presentacion.botonCircular();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paneldinamicoMatches = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        btnBuscarEstudiantes3.setBackground(new java.awt.Color(102, 204, 255));
        btnBuscarEstudiantes3.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEstudiantes3.setText("Buscar estudiantes");
        btnBuscarEstudiantes3.setBorderColor(new java.awt.Color(255, 255, 255));
        btnBuscarEstudiantes3.setColor(new java.awt.Color(102, 204, 255));
        btnBuscarEstudiantes3.setColorClick(new java.awt.Color(102, 204, 255));
        btnBuscarEstudiantes3.setColorOver(new java.awt.Color(51, 204, 255));
        btnBuscarEstudiantes3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnBuscarEstudiantes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstudiantes3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(247, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnInicio3.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hogar.png"))); // NOI18N
        btnInicio3.setText("Inicio");
        btnInicio3.setBorderColor(new java.awt.Color(255, 255, 255));
        btnInicio3.setColorClick(new java.awt.Color(102, 204, 255));
        btnInicio3.setColorOver(new java.awt.Color(102, 204, 255));
        btnInicio3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnInicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicio3ActionPerformed(evt);
            }
        });

        btnMatches3.setForeground(new java.awt.Color(0, 0, 0));
        btnMatches3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amigos-felices.png"))); // NOI18N
        btnMatches3.setText("Matches");
        btnMatches3.setBorderColor(new java.awt.Color(255, 255, 255));
        btnMatches3.setColorClick(new java.awt.Color(102, 204, 255));
        btnMatches3.setColorOver(new java.awt.Color(102, 204, 255));
        btnMatches3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnMatches3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatches3ActionPerformed(evt);
            }
        });

        btnMensajes3.setForeground(new java.awt.Color(0, 0, 0));
        btnMensajes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mensajero.png"))); // NOI18N
        btnMensajes3.setText("Mensajes");
        btnMensajes3.setBorderColor(new java.awt.Color(255, 255, 255));
        btnMensajes3.setColorClick(new java.awt.Color(102, 204, 255));
        btnMensajes3.setColorOver(new java.awt.Color(102, 204, 255));
        btnMensajes3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnMensajes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensajes3ActionPerformed(evt);
            }
        });

        btnPerfil3.setForeground(new java.awt.Color(0, 0, 0));
        btnPerfil3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar (2).png"))); // NOI18N
        btnPerfil3.setText("Perfil");
        btnPerfil3.setBorderColor(new java.awt.Color(255, 255, 255));
        btnPerfil3.setColorClick(new java.awt.Color(102, 204, 255));
        btnPerfil3.setColorOver(new java.awt.Color(102, 204, 255));
        btnPerfil3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnPerfil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfil3ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario (2).png"))); // NOI18N

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre estudiante");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInicio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(btnMatches3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMensajes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPerfil3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9)))
                .addGap(29, 29, 29)
                .addComponent(btnInicio3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMatches3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMensajes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPerfil3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneldinamicoMatches.setBackground(new java.awt.Color(255, 255, 255));
        paneldinamicoMatches.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout paneldinamicoMatchesLayout = new javax.swing.GroupLayout(paneldinamicoMatches);
        paneldinamicoMatches.setLayout(paneldinamicoMatchesLayout);
        paneldinamicoMatchesLayout.setHorizontalGroup(
            paneldinamicoMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        paneldinamicoMatchesLayout.setVerticalGroup(
            paneldinamicoMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(paneldinamicoMatches);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Mis Macthes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarEstudiantes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstudiantes3ActionPerformed
        
    }//GEN-LAST:event_btnBuscarEstudiantes3ActionPerformed

    private void btnInicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicio3ActionPerformed

    private void btnMatches3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatches3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMatches3ActionPerformed

    private void btnMensajes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensajes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMensajes3ActionPerformed

    private void btnPerfil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfil3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfil3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matchesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matchesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matchesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matchesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matchesFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentacion.botonCircular btnBuscarEstudiantes;
    private presentacion.botonCircular btnBuscarEstudiantes1;
    private presentacion.botonCircular btnBuscarEstudiantes2;
    private presentacion.botonCircular btnBuscarEstudiantes3;
    private presentacion.botonCircular btnInicio;
    private presentacion.botonCircular btnInicio1;
    private presentacion.botonCircular btnInicio2;
    private presentacion.botonCircular btnInicio3;
    private presentacion.botonCircular btnMatches;
    private presentacion.botonCircular btnMatches1;
    private presentacion.botonCircular btnMatches2;
    private presentacion.botonCircular btnMatches3;
    private presentacion.botonCircular btnMensajes;
    private presentacion.botonCircular btnMensajes1;
    private presentacion.botonCircular btnMensajes2;
    private presentacion.botonCircular btnMensajes3;
    private presentacion.botonCircular btnPerfil;
    private presentacion.botonCircular btnPerfil1;
    private presentacion.botonCircular btnPerfil2;
    private presentacion.botonCircular btnPerfil3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel paneldinamicoMatches;
    // End of variables declaration//GEN-END:variables
}
