/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import dto.EstudianteDTO;
import dto.MatchDTO;
import java.awt.Color;
import java.awt.GridLayout;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.concurrent.Executors;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author USER
 */
public class matchesFrm extends javax.swing.JFrame {

    private EstudianteDTO estudianteLogueado;
    private EstudianteDTO estudianteActual;
    private final ObjectMapper objectMapper = new ObjectMapper();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(matchesFrm.class.getName());

    public matchesFrm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public matchesFrm(EstudianteDTO estudianteActual) {
        this.estudianteLogueado = estudianteActual;

        this.estudianteActual = estudianteActual;
        initComponents();

        setLocationRelativeTo(null);
        setTitle("Matches de " + estudianteActual.getNombre());
        lblNombreEstudiante.setText(estudianteActual.getNombre());

        paneldinamicoMatches.setLayout(new GridLayout(0, 1, 10, 10)); 
        paneldinamicoMatches.setBackground(Color.WHITE);

        cargarMatches();

    }

    private void cargarMatches() {
        if (estudianteActual == null) {
            JOptionPane.showMessageDialog(this, "Error: No se ha iniciado sesion.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Executors.newSingleThreadExecutor().submit(() -> {
            try {
                HttpClient client = HttpClient.newHttpClient();
                String url = "http://localhost:8080/api/estudiantes/" + estudianteActual.getId() + "/matches";

                HttpRequest request = HttpRequest.newBuilder()
                        .uri(URI.create(url))
                        .GET()
                        .build();

                HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

                if (response.statusCode() == 200) {
                    List<MatchDTO> matches = objectMapper.readValue(response.body(), new TypeReference<List<MatchDTO>>() {
                    });

                    SwingUtilities.invokeLater(() -> {
                        mostrarMatches(matches);
                    });
                } else {
                    SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, "Error al cargar matches: " + response.body(), "Error", JOptionPane.ERROR_MESSAGE));
                }
            } catch (Exception e) {
                logger.log(java.util.logging.Level.SEVERE, "Error al cargar matches", e);
                SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, "Error de conexion: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE));
            }
        });
    }

    private void mostrarMatches(List<MatchDTO> matches) {
        paneldinamicoMatches.removeAll();

        if (matches.isEmpty()) {
            JLabel lblVacio = new JLabel("Aún no tienes matches. ¡Sigue descubriendo!");
            lblVacio.setHorizontalAlignment(JLabel.CENTER);
            paneldinamicoMatches.add(lblVacio);
        }

        for (MatchDTO m : matches) {
            EstudianteDTO otroParticipante = null;
            for (EstudianteDTO participante : m.getParticipantes()) {
                if (!participante.getId().equals(this.estudianteActual.getId())) {
                    otroParticipante = participante;
                    break;
                }
            }

            if (otroParticipante != null) {
                PanelAvatarMacthes panel = new PanelAvatarMacthes(
                        this.estudianteActual,
                        m,
                        otroParticipante
                );
                paneldinamicoMatches.add(panel);
            }
        }

        paneldinamicoMatches.revalidate();
        paneldinamicoMatches.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarEstudiantes3 = new presentacion.botonCircular();
        btnMensajes3 = new presentacion.botonCircular();
        btnPerfil1 = new presentacion.botonCircular();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnInicio3 = new presentacion.botonCircular();
        btnMatches3 = new presentacion.botonCircular();
        btnPerfil3 = new presentacion.botonCircular();
        jLabel8 = new javax.swing.JLabel();
        lblNombreEstudiante = new javax.swing.JLabel();
        btnPerfil2 = new presentacion.botonCircular();
        jScrollPane1 = new javax.swing.JScrollPane();
        paneldinamicoMatches = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldRedondo1 = new presentacion.TextFieldRedondo();
        jButton1 = new javax.swing.JButton();

        btnBuscarEstudiantes3.setBackground(new java.awt.Color(102, 204, 255));
        btnBuscarEstudiantes3.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEstudiantes3.setText("Buscar estudiantes");
        btnBuscarEstudiantes3.setBorderColor(new java.awt.Color(255, 255, 255));
        btnBuscarEstudiantes3.setColor(new java.awt.Color(102, 204, 255));
        btnBuscarEstudiantes3.setColorClick(new java.awt.Color(102, 204, 255));
        btnBuscarEstudiantes3.setColorOver(new java.awt.Color(51, 204, 255));
        btnBuscarEstudiantes3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnBuscarEstudiantes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstudiantes3ActionPerformed(evt);
            }
        });

        btnMensajes3.setForeground(new java.awt.Color(0, 0, 0));
        btnMensajes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mensajero.png"))); // NOI18N
        btnMensajes3.setText("Mensajes");
        btnMensajes3.setBorderColor(new java.awt.Color(255, 255, 255));
        btnMensajes3.setColorClick(new java.awt.Color(102, 204, 255));
        btnMensajes3.setColorOver(new java.awt.Color(102, 204, 255));
        btnMensajes3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnMensajes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensajes3ActionPerformed(evt);
            }
        });

        btnPerfil1.setForeground(new java.awt.Color(0, 0, 0));
        btnPerfil1.setText("Cerrar sesion");
        btnPerfil1.setBorderColor(new java.awt.Color(255, 255, 255));
        btnPerfil1.setColorClick(new java.awt.Color(102, 204, 255));
        btnPerfil1.setColorOver(new java.awt.Color(102, 204, 255));
        btnPerfil1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnPerfil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfil1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(247, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnInicio3.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hogar.png"))); // NOI18N
        btnInicio3.setText("Inicio");
        btnInicio3.setBorderColor(new java.awt.Color(204, 255, 255));
        btnInicio3.setColorClick(new java.awt.Color(102, 204, 255));
        btnInicio3.setColorOver(new java.awt.Color(102, 204, 255));
        btnInicio3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnInicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicio3ActionPerformed(evt);
            }
        });

        btnMatches3.setForeground(new java.awt.Color(0, 0, 0));
        btnMatches3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amigos-felices.png"))); // NOI18N
        btnMatches3.setText("Matches");
        btnMatches3.setBorderColor(new java.awt.Color(204, 255, 255));
        btnMatches3.setColorClick(new java.awt.Color(102, 204, 255));
        btnMatches3.setColorOver(new java.awt.Color(102, 204, 255));
        btnMatches3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnMatches3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatches3ActionPerformed(evt);
            }
        });

        btnPerfil3.setForeground(new java.awt.Color(0, 0, 0));
        btnPerfil3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar (2).png"))); // NOI18N
        btnPerfil3.setText("Perfil");
        btnPerfil3.setBorderColor(new java.awt.Color(204, 255, 255));
        btnPerfil3.setColorClick(new java.awt.Color(102, 204, 255));
        btnPerfil3.setColorOver(new java.awt.Color(102, 204, 255));
        btnPerfil3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnPerfil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfil3ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario (2).png"))); // NOI18N

        lblNombreEstudiante.setBackground(new java.awt.Color(0, 0, 0));
        lblNombreEstudiante.setFont(new java.awt.Font("SansSerif", 3, 16)); // NOI18N
        lblNombreEstudiante.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreEstudiante.setText("Nombre estudiante");

        btnPerfil2.setForeground(new java.awt.Color(0, 0, 0));
        btnPerfil2.setText("Cerrar sesion");
        btnPerfil2.setBorderColor(new java.awt.Color(204, 255, 255));
        btnPerfil2.setColorClick(new java.awt.Color(102, 204, 255));
        btnPerfil2.setColorOver(new java.awt.Color(102, 204, 255));
        btnPerfil2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnPerfil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfil2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInicio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMatches3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPerfil3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPerfil2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreEstudiante)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblNombreEstudiante)))
                .addGap(29, 29, 29)
                .addComponent(btnInicio3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMatches3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPerfil3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPerfil2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneldinamicoMatches.setBackground(new java.awt.Color(255, 255, 255));
        paneldinamicoMatches.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout paneldinamicoMatchesLayout = new javax.swing.GroupLayout(paneldinamicoMatches);
        paneldinamicoMatches.setLayout(paneldinamicoMatchesLayout);
        paneldinamicoMatchesLayout.setHorizontalGroup(
            paneldinamicoMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        paneldinamicoMatchesLayout.setVerticalGroup(
            paneldinamicoMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(paneldinamicoMatches);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Mis Macthes");

        jButton1.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(textFieldRedondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldRedondo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarEstudiantes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstudiantes3ActionPerformed

    }//GEN-LAST:event_btnBuscarEstudiantes3ActionPerformed

    private void btnInicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicio3ActionPerformed
        if (this.estudianteLogueado == null) {
            JOptionPane.showMessageDialog(this, "Error de sesion. Intente iniciar sesion de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
            new inicioConnectFrm().setVisible(true);
            this.dispose();
            return;
            
        }
        inicioConnectFrm inicio = new inicioConnectFrm(this.estudianteLogueado);
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicio3ActionPerformed

    private void btnMatches3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatches3ActionPerformed
        if (this.estudianteLogueado == null) {
            JOptionPane.showMessageDialog(this, "Error de sesion. Intente iniciar sesion de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
            new matchesFrm().setVisible(true);
            this.dispose();
            return;
        }
        matchesFrm matchesVentana = new matchesFrm(this.estudianteLogueado);
        matchesVentana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMatches3ActionPerformed

    private void btnMensajes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensajes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMensajes3ActionPerformed

    private void btnPerfil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfil3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfil3ActionPerformed

    private void btnPerfil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfil1ActionPerformed

    private void btnPerfil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfil2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matchesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matchesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matchesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matchesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matchesFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentacion.botonCircular btnBuscarEstudiantes3;
    private presentacion.botonCircular btnInicio3;
    private presentacion.botonCircular btnMatches3;
    private presentacion.botonCircular btnMensajes3;
    private presentacion.botonCircular btnPerfil1;
    private presentacion.botonCircular btnPerfil2;
    private presentacion.botonCircular btnPerfil3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreEstudiante;
    private javax.swing.JPanel paneldinamicoMatches;
    private presentacion.TextFieldRedondo textFieldRedondo1;
    // End of variables declaration//GEN-END:variables
}
