/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import service.IMatchService;

/**
 *
 * @author jorge
 */
public class MatchesFrm extends javax.swing.JFrame {
    
     private IMatchService matchService;
    private Long estudianteActualId;
    /**
     * Creates new form MatchesFrm
     */
    public MatchesFrm() {
        initComponents();
    }
    
     private void inicializarMatches() {
        // Crear el panel contenedor con GridLayout
        contenedorMatches = new JPanel();
        contenedorMatches.setLayout(new GridLayout(0, 3, 15, 15)); // 3 columnas
        contenedorMatches.setBackground(Color.WHITE);
        contenedorMatches.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
        
        // Agregar el contenedor al ScrollPane
        jScrollPane1.setViewportView(contenedorMatches);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        
        // Inicializar el servicio
        matchService = new MatchService();
        
        // Cargar matches desde la API
        if (estudianteActualId != null) {
            cargarMatches();
        } else {
            // Si no hay estudiante, mostrar mensaje
            JLabel mensaje = new JLabel("Inicia sesión para ver tus matches");
            mensaje.setHorizontalAlignment(SwingConstants.CENTER);
            contenedorMatches.add(mensaje);
        }
    }
    
    // ===== MÉTODO PARA CARGAR MATCHES DESDE LA API =====
    private void cargarMatches() {
        // Limpiar contenedor
        contenedorMatches.removeAll();
        
        // Mostrar loading
        JLabel loading = new JLabel("Cargando matches...");
        loading.setHorizontalAlignment(SwingConstants.CENTER);
        loading.setFont(new Font("SansSerif", Font.PLAIN, 14));
        contenedorMatches.add(loading);
        contenedorMatches.revalidate();
        contenedorMatches.repaint();
        
        // Cargar en segundo plano
        SwingWorker<List<MatchDTO>, Void> worker = new SwingWorker<>() {
            @Override
            protected List<MatchDTO> doInBackground() throws Exception {
                return matchService.obtenerMatchesDeEstudiante(estudianteActualId);
            }
            
            @Override
            protected void done() {
                contenedorMatches.removeAll();
                
                try {
                    List<MatchDTO> matches = get();
                    
                    if (matches.isEmpty()) {
                        JLabel noMatches = new JLabel("No tienes matches aún 💔");
                        noMatches.setHorizontalAlignment(SwingConstants.CENTER);
                        noMatches.setFont(new Font("SansSerif", Font.BOLD, 16));
                        contenedorMatches.add(noMatches);
                    } else {
                        // Por cada match, crear un PanelAvatarMatches
                        for (MatchDTO match : matches) {
                            // Obtener el ID del otro participante
                            Long otroEstudianteId = match.getParticipanteIds().stream()
                                .filter(id -> !id.equals(estudianteActualId))
                                .findFirst()
                                .orElse(null);
                            
                            if (otroEstudianteId != null) {
                                cargarPanelMatch(match, otroEstudianteId);
                            }
                        }
                    }
                } catch (Exception e) {
                    JLabel error = new JLabel("Error al cargar matches: " + e.getMessage());
                    error.setHorizontalAlignment(SwingConstants.CENTER);
                    error.setForeground(Color.RED);
                    contenedorMatches.add(error);
                    e.printStackTrace();
                }
                
                contenedorMatches.revalidate();
                contenedorMatches.repaint();
            }
        };
        worker.execute();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonCircular2 = new presentacion.botonCircular();
        botonCircular3 = new presentacion.botonCircular();
        botonCircular4 = new presentacion.botonCircular();
        botonCircular5 = new presentacion.botonCircular();
        botonCircular1 = new presentacion.botonCircular();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        contenedorMatches = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(940, 497));

        jPanel2.setBackground(new java.awt.Color(247, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 364));

        jLabel1.setText("Nombre Usuario");
        jLabel1.setPreferredSize(new java.awt.Dimension(102, 16));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario (2).png"))); // NOI18N
        jLabel2.setText("jLabel2");

        botonCircular2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hogar.png"))); // NOI18N
        botonCircular2.setText("Inicio");
        botonCircular2.setBorderColor(new java.awt.Color(255, 255, 255));
        botonCircular2.setColorClick(new java.awt.Color(102, 204, 255));
        botonCircular2.setColorOver(new java.awt.Color(102, 204, 255));
        botonCircular2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        botonCircular2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCircular2ActionPerformed(evt);
            }
        });

        botonCircular3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amigos-felices.png"))); // NOI18N
        botonCircular3.setText("Matches");
        botonCircular3.setBorderColor(new java.awt.Color(255, 255, 255));
        botonCircular3.setColorClick(new java.awt.Color(102, 204, 255));
        botonCircular3.setColorOver(new java.awt.Color(102, 204, 255));
        botonCircular3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        botonCircular3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCircular3ActionPerformed(evt);
            }
        });

        botonCircular4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mensajero.png"))); // NOI18N
        botonCircular4.setText("Mensajes");
        botonCircular4.setBorderColor(new java.awt.Color(255, 255, 255));
        botonCircular4.setColorClick(new java.awt.Color(102, 204, 255));
        botonCircular4.setColorOver(new java.awt.Color(102, 204, 255));
        botonCircular4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        botonCircular4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCircular4ActionPerformed(evt);
            }
        });

        botonCircular5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar (2).png"))); // NOI18N
        botonCircular5.setText("Perfil");
        botonCircular5.setBorderColor(new java.awt.Color(255, 255, 255));
        botonCircular5.setColorClick(new java.awt.Color(102, 204, 255));
        botonCircular5.setColorOver(new java.awt.Color(102, 204, 255));
        botonCircular5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        botonCircular5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCircular5ActionPerformed(evt);
            }
        });

        botonCircular1.setBackground(new java.awt.Color(102, 204, 255));
        botonCircular1.setForeground(new java.awt.Color(255, 255, 255));
        botonCircular1.setText("Buscar estudiantes");
        botonCircular1.setBorderColor(new java.awt.Color(255, 255, 255));
        botonCircular1.setColor(new java.awt.Color(102, 204, 255));
        botonCircular1.setColorClick(new java.awt.Color(102, 204, 255));
        botonCircular1.setColorOver(new java.awt.Color(51, 204, 255));
        botonCircular1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botonCircular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCircular1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonCircular2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonCircular3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonCircular4, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonCircular5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonCircular1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(botonCircular2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCircular3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCircular4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCircular5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(botonCircular1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        jLabel4.setText("Matches");

        javax.swing.GroupLayout contenedorMatchesLayout = new javax.swing.GroupLayout(contenedorMatches);
        contenedorMatches.setLayout(contenedorMatchesLayout);
        contenedorMatchesLayout.setHorizontalGroup(
            contenedorMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );
        contenedorMatchesLayout.setVerticalGroup(
            contenedorMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(contenedorMatches);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCircular2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCircular2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCircular2ActionPerformed

    private void botonCircular3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCircular3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCircular3ActionPerformed

    private void botonCircular4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCircular4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCircular4ActionPerformed

    private void botonCircular5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCircular5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCircular5ActionPerformed

    private void botonCircular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCircular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCircular1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatchesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatchesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatchesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatchesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatchesFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentacion.botonCircular botonCircular1;
    private presentacion.botonCircular botonCircular2;
    private presentacion.botonCircular botonCircular3;
    private presentacion.botonCircular botonCircular4;
    private presentacion.botonCircular botonCircular5;
    private javax.swing.JPanel contenedorMatches;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
