/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.util.Base64;
import javax.swing.ImageIcon;

/**
 *
 * @author USER
 */
public class PersonasFrm extends javax.swing.JPanel {

    private Long emisorId;
    private Long receptorId;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PersonasFrm.class.getName());

    /**
     * Creates new form PersonasFrm
     */
    public PersonasFrm() {
        initComponents();
    }
   
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblFotoPerfil = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblHobbys = new javax.swing.JLabel();
        btnNoMeInteresa = new presentacion.botonCircular();
        btnMegusta = new presentacion.botonCircular();

        jLabel3.setText("jLabel3");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblNombre.setText("jLabel1");

        lblHobbys.setText("jLabel2");

        btnNoMeInteresa.setForeground(new java.awt.Color(153, 0, 0));
        btnNoMeInteresa.setText("no me interesa");
        btnNoMeInteresa.setBorderColor(new java.awt.Color(255, 255, 255));
        btnNoMeInteresa.setColor(new java.awt.Color(255, 204, 204));
        btnNoMeInteresa.setColorClick(new java.awt.Color(255, 51, 51));
        btnNoMeInteresa.setColorOver(new java.awt.Color(255, 204, 204));
        btnNoMeInteresa.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N

        btnMegusta.setBackground(new java.awt.Color(102, 204, 255));
        btnMegusta.setForeground(new java.awt.Color(255, 255, 255));
        btnMegusta.setText("Me gusta");
        btnMegusta.setBorderColor(new java.awt.Color(255, 255, 255));
        btnMegusta.setColor(new java.awt.Color(102, 204, 255));
        btnMegusta.setColorClick(new java.awt.Color(102, 204, 255));
        btnMegusta.setColorOver(new java.awt.Color(51, 153, 255));
        btnMegusta.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblHobbys)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNoMeInteresa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMegusta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFotoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblNombre)
                .addGap(44, 44, 44)
                .addComponent(lblHobbys)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNoMeInteresa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMegusta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentacion.botonCircular btnMegusta;
    private presentacion.botonCircular btnNoMeInteresa;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFotoPerfil;
    private javax.swing.JLabel lblHobbys;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
