/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import com.fasterxml.jackson.databind.ObjectMapper;
import dto.EstudianteDTO;
import java.awt.Image;
import java.io.File;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.util.Base64;
import java.util.HashSet;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import static org.hibernate.internal.CoreLogging.logger;
import static org.hibernate.internal.HEMLogging.logger;

/**
 *
 * @author USER
 */
public class RegistrarFrm extends javax.swing.JFrame {
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrarFrm.class.getName());
    private byte[] fotoBytes;
    
    public RegistrarFrm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        passwordFieldRedondo1 = new presentacion.PasswordFieldRedondo();
        botonCircular2 = new presentacion.botonCircular();
        passwordFieldRedondo2 = new presentacion.PasswordFieldRedondo();
        textFieldRedondo4 = new presentacion.TextFieldRedondo();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        passwordFieldRedondo4 = new presentacion.PasswordFieldRedondo();
        panelRedondo4 = new presentacion.PanelRedondo();
        textFieldRedondo5 = new presentacion.TextFieldRedondo();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        btnIniciarSesion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelRedondo1 = new presentacion.PanelRedondo();
        jLabel3 = new javax.swing.JLabel();
        panelRedondo3 = new presentacion.PanelRedondo();
        lblImagen = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new presentacion.TextFieldRedondo();
        jLabel5 = new javax.swing.JLabel();
        txtApellidoPaterno = new presentacion.TextFieldRedondo();
        jLabel6 = new javax.swing.JLabel();
        txtApellidoMaterno = new presentacion.TextFieldRedondo();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCrearCuenta = new presentacion.botonCircular();
        jLabel9 = new javax.swing.JLabel();
        btnInicioSesion = new presentacion.botonCircular();
        passContresena = new presentacion.PasswordFieldRedondo();
        panelRedondo2 = new presentacion.PanelRedondo();
        jLabel10 = new javax.swing.JLabel();
        btnAgregarFoto = new presentacion.botonCircular();
        jLabel13 = new javax.swing.JLabel();
        passConfirmarContra = new presentacion.PasswordFieldRedondo();
        panelRedondo5 = new presentacion.PanelRedondo();
        checkGaming = new javax.swing.JCheckBox();
        checkDeportes = new javax.swing.JCheckBox();
        checkPeliculas = new javax.swing.JCheckBox();
        checkViajes = new javax.swing.JCheckBox();
        checkLectura = new javax.swing.JCheckBox();
        checkCantar = new javax.swing.JCheckBox();
        chekCodificar = new javax.swing.JCheckBox();
        checkMusica = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        txtCorreoInstituto = new presentacion.TextFieldRedondo();

        jLabel2.setText("jLabel2");

        passwordFieldRedondo1.setText("passwordFieldRedondo1");

        botonCircular2.setForeground(new java.awt.Color(30, 115, 179));
        botonCircular2.setText("Crear ahorra");
        botonCircular2.setBorderColor(new java.awt.Color(255, 255, 255));
        botonCircular2.setColorClick(new java.awt.Color(255, 255, 255));
        botonCircular2.setColorOver(new java.awt.Color(153, 255, 255));
        botonCircular2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        botonCircular2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCircular2ActionPerformed(evt);
            }
        });

        passwordFieldRedondo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldRedondo2ActionPerformed(evt);
            }
        });

        textFieldRedondo4.setText("textFieldRedondo4");

        jLabel11.setText("jLabel11");

        jButton1.setText("Agregar Foto");

        jLabel12.setText("jLabel12");

        passwordFieldRedondo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldRedondo4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRedondo4Layout = new javax.swing.GroupLayout(panelRedondo4);
        panelRedondo4.setLayout(panelRedondo4Layout);
        panelRedondo4Layout.setHorizontalGroup(
            panelRedondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelRedondo4Layout.setVerticalGroup(
            panelRedondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jCheckBox7.setText("jCheckBox7");

        jCheckBox3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jCheckBox3.setText("Deportes");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIniciarSesion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Crea tu cuenta en ItsonConnect");

        panelRedondo1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Foto de perfil");

        panelRedondo3.setBackground(new java.awt.Color(255, 255, 255));
        panelRedondo3.setRadius(100);

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssss.jpg"))); // NOI18N

        javax.swing.GroupLayout panelRedondo3Layout = new javax.swing.GroupLayout(panelRedondo3);
        panelRedondo3.setLayout(panelRedondo3Layout);
        panelRedondo3Layout.setHorizontalGroup(
            panelRedondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondo3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelRedondo3Layout.setVerticalGroup(
            panelRedondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelRedondo1Layout = new javax.swing.GroupLayout(panelRedondo1);
        panelRedondo1.setLayout(panelRedondo1Layout);
        panelRedondo1Layout.setHorizontalGroup(
            panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondo1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRedondo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRedondo1Layout.setVerticalGroup(
            panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondo1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRedondo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apellido Paterno:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Apellido Materno:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Contraseña:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Confirma Contraseña:");

        btnCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setText("Crear Cuenta");
        btnCrearCuenta.setBorderColor(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setColor(new java.awt.Color(102, 204, 255));
        btnCrearCuenta.setColorClick(new java.awt.Color(102, 255, 255));
        btnCrearCuenta.setColorOver(new java.awt.Color(153, 255, 255));
        btnCrearCuenta.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Ya tienes una cuenta?");

        btnInicioSesion.setForeground(new java.awt.Color(30, 115, 179));
        btnInicioSesion.setText("Iniciar Sesion");
        btnInicioSesion.setBorderColor(new java.awt.Color(255, 255, 255));
        btnInicioSesion.setColorClick(new java.awt.Color(255, 255, 255));
        btnInicioSesion.setColorOver(new java.awt.Color(153, 255, 255));
        btnInicioSesion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });

        passContresena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passContresenaActionPerformed(evt);
            }
        });

        panelRedondo2.setBackground(new java.awt.Color(234, 231, 225));
        panelRedondo2.setRadius(30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unnamed.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout panelRedondo2Layout = new javax.swing.GroupLayout(panelRedondo2);
        panelRedondo2.setLayout(panelRedondo2Layout);
        panelRedondo2Layout.setHorizontalGroup(
            panelRedondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondo2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        panelRedondo2Layout.setVerticalGroup(
            panelRedondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondo2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAgregarFoto.setBackground(new java.awt.Color(30, 115, 179));
        btnAgregarFoto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarFoto.setText("Agregar Foto");
        btnAgregarFoto.setBorderColor(new java.awt.Color(255, 255, 255));
        btnAgregarFoto.setColor(new java.awt.Color(30, 115, 179));
        btnAgregarFoto.setColorClick(new java.awt.Color(30, 115, 179));
        btnAgregarFoto.setColorOver(new java.awt.Color(0, 204, 204));
        btnAgregarFoto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAgregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFotoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Hobbys y Intereses");

        passConfirmarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passConfirmarContraActionPerformed(evt);
            }
        });

        panelRedondo5.setBackground(new java.awt.Color(234, 231, 225));

        checkGaming.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        checkGaming.setText("Gaming");

        checkDeportes.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        checkDeportes.setText("Deportes");

        checkPeliculas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        checkPeliculas.setText("Peliculas");

        checkViajes.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        checkViajes.setText("Viajes");

        checkLectura.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        checkLectura.setText("Lectura");

        checkCantar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        checkCantar.setText("Cantar");
        checkCantar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCantarActionPerformed(evt);
            }
        });

        chekCodificar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        chekCodificar.setText("Codificar");
        chekCodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekCodificarActionPerformed(evt);
            }
        });

        checkMusica.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        checkMusica.setText("Musica");

        javax.swing.GroupLayout panelRedondo5Layout = new javax.swing.GroupLayout(panelRedondo5);
        panelRedondo5.setLayout(panelRedondo5Layout);
        panelRedondo5Layout.setHorizontalGroup(
            panelRedondo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondo5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRedondo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRedondo5Layout.createSequentialGroup()
                        .addComponent(checkGaming, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(checkMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRedondo5Layout.createSequentialGroup()
                        .addComponent(checkViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkLectura, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkCantar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(chekCodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelRedondo5Layout.setVerticalGroup(
            panelRedondo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondo5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelRedondo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkGaming, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRedondo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkLectura, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkCantar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chekCodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Correo Institucional:");

        javax.swing.GroupLayout btnIniciarSesionLayout = new javax.swing.GroupLayout(btnIniciarSesion);
        btnIniciarSesion.setLayout(btnIniciarSesionLayout);
        btnIniciarSesionLayout.setHorizontalGroup(
            btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIniciarSesionLayout.createSequentialGroup()
                .addGroup(btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnIniciarSesionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(btnIniciarSesionLayout.createSequentialGroup()
                                .addGroup(btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panelRedondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAgregarFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtCorreoInstituto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(btnIniciarSesionLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(btnIniciarSesionLayout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(btnIniciarSesionLayout.createSequentialGroup()
                                        .addGroup(btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(passContresena, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(passConfirmarContra, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnIniciarSesionLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(panelRedondo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(panelRedondo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnIniciarSesionLayout.setVerticalGroup(
            btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIniciarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelRedondo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btnIniciarSesionLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addGroup(btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnIniciarSesionLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCorreoInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(btnIniciarSesionLayout.createSequentialGroup()
                                .addComponent(panelRedondo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(btnIniciarSesionLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passConfirmarContra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(btnIniciarSesionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passContresena, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRedondo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(btnInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldRedondo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldRedondo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldRedondo2ActionPerformed

    private void passwordFieldRedondo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldRedondo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldRedondo4ActionPerformed

    private void botonCircular2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCircular2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCircular2ActionPerformed

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        IniciarSesionFrm iniciarSesion = new IniciarSesionFrm();
        iniciarSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    private void passContresenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passContresenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passContresenaActionPerformed

    private void passConfirmarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passConfirmarContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passConfirmarContraActionPerformed

    private void chekCodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekCodificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chekCodificarActionPerformed

    private void checkCantarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCantarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkCantarActionPerformed

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        try {
            String nombre = txtNombre.getText();
            String apPaterno = txtApellidoPaterno.getText();
            String apMaterno = txtApellidoMaterno.getText();
            String correo = txtCorreoInstituto.getText();
            String password = new String(passConfirmarContra.getPassword());
            String confirmPass = new String(passConfirmarContra.getPassword());
            
            if (nombre.isEmpty() || apPaterno.isEmpty() || correo.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nombre, Apellido Paterno, Correo y Contraseña son obligatorios.", "Error de Validacion", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!password.equals(confirmPass)) {
                JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.", "Error de Validacion", JOptionPane.ERROR_MESSAGE);
                return;
            }
            //partes de los hobbies y la foto
            Set<String>hobbiesSeleccionados = new HashSet<>();
           if (checkGaming.isSelected()) hobbiesSeleccionados.add("Gaming");
            if (checkMusica.isSelected()) hobbiesSeleccionados.add("Musica");
            if (checkDeportes.isSelected()) hobbiesSeleccionados.add("Deportes");
            if (checkPeliculas.isSelected()) hobbiesSeleccionados.add("Peliculas");
            if (checkViajes.isSelected()) hobbiesSeleccionados.add("Viajes");
            if (checkLectura.isSelected()) hobbiesSeleccionados.add("Lectura");
            if (checkCantar.isSelected()) hobbiesSeleccionados.add("Cantar");
            if (chekCodificar.isSelected()) hobbiesSeleccionados.add("Codificar");
         
            //aqui crea los dto y los convierte a json
            EstudianteDTO nuevoEstudiante = new EstudianteDTO();
            nuevoEstudiante.setNombre(nombre);
            nuevoEstudiante.setApPaterno(apPaterno);
            nuevoEstudiante.setApMaterno(apMaterno);
            nuevoEstudiante.setCorreo(correo);
            nuevoEstudiante.setPassword(password);
            
            //logica de la foto
            if(this.fotoBytes != null){
                nuevoEstudiante.setFotoBase64(Base64.getEncoder().encodeToString(this.fotoBytes));
            }
            
            
            
            ObjectMapper objectMapper = new ObjectMapper();
            String requestBody = objectMapper.writeValueAsString(nuevoEstudiante);
            
            HttpClient client = HttpClient.newHttpClient();
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create("http://localhost:8080/api/estudiantes")) 
                    .POST(HttpRequest.BodyPublishers.ofString(requestBody))
                    .header("Content-Type", "application/json")
                    .build();
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            
            if(response.statusCode()== 201){ //201 significa creado
                JOptionPane.showMessageDialog(this, "¡Cuenta creada exitosamente! Ahora inicia sesion.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
                
                IniciarSesionFrm loginFrm = new IniciarSesionFrm();
                loginFrm.setVisible(true);
                this.dispose();
            }else{
                String errorMessage = response.body();
                JOptionPane.showMessageDialog(this, "Error: " + errorMessage, "Fallo de Registro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error al registrar", e);
            JOptionPane.showMessageDialog(this, "Error de conexion con el servidor: " + e.getMessage(), "Error de Conexion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void btnAgregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFotoActionPerformed
       JFileChooser fileChooser = new JFileChooser();
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagenes (JPG, PNG, GIF)", "jpg", "png", "gif");
        fileChooser.setFileFilter(filter);

        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            try {
                File archivoSeleccionado = fileChooser.getSelectedFile();
                
             
                this.fotoBytes = Files.readAllBytes(archivoSeleccionado.toPath());
                
          
                ImageIcon icon = new ImageIcon(archivoSeleccionado.getAbsolutePath());
               
                Image imagen = icon.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH);
                lblImagen.setIcon(new ImageIcon(imagen));
                
                JOptionPane.showMessageDialog(this, "Foto cargada exitosamente.");
                
            } catch (Exception e) {
                logger.log(java.util.logging.Level.SEVERE, "Error al leer la imagen", e);
                JOptionPane.showMessageDialog(this, "Error al cargar la foto: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                this.fotoBytes = null; 
            }
        }
    }//GEN-LAST:event_btnAgregarFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentacion.botonCircular botonCircular2;
    private presentacion.botonCircular btnAgregarFoto;
    private presentacion.botonCircular btnCrearCuenta;
    private javax.swing.JPanel btnIniciarSesion;
    private presentacion.botonCircular btnInicioSesion;
    private javax.swing.JCheckBox checkCantar;
    private javax.swing.JCheckBox checkDeportes;
    private javax.swing.JCheckBox checkGaming;
    private javax.swing.JCheckBox checkLectura;
    private javax.swing.JCheckBox checkMusica;
    private javax.swing.JCheckBox checkPeliculas;
    private javax.swing.JCheckBox checkViajes;
    private javax.swing.JCheckBox chekCodificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblImagen;
    private presentacion.PanelRedondo panelRedondo1;
    private presentacion.PanelRedondo panelRedondo2;
    private presentacion.PanelRedondo panelRedondo3;
    private presentacion.PanelRedondo panelRedondo4;
    private presentacion.PanelRedondo panelRedondo5;
    private presentacion.PasswordFieldRedondo passConfirmarContra;
    private presentacion.PasswordFieldRedondo passContresena;
    private presentacion.PasswordFieldRedondo passwordFieldRedondo1;
    private presentacion.PasswordFieldRedondo passwordFieldRedondo2;
    private presentacion.PasswordFieldRedondo passwordFieldRedondo4;
    private presentacion.TextFieldRedondo textFieldRedondo4;
    private presentacion.TextFieldRedondo textFieldRedondo5;
    private presentacion.TextFieldRedondo txtApellidoMaterno;
    private presentacion.TextFieldRedondo txtApellidoPaterno;
    private presentacion.TextFieldRedondo txtCorreoInstituto;
    private presentacion.TextFieldRedondo txtNombre;
    // End of variables declaration//GEN-END:variables
}
